pragmatic-programmer.pdf: pragmatic-programmer.tex ../ost-summary-template.tex
	latexmk -pdf -shell-escape pragmatic-programmer.tex

clean:
	(rm -f *.aux *.fdb_latexmk *.fls *.log *.out *.synctex.gz *.xdv);\

move: 
	cp pragmatic-programmer.pdf $${HOME}/Documents/OST\ 4.semester/pragmatic-programmer.pdf
